# Generated by Django 6.0.1 on 2026-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_id',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
