# Generated by Django 6.0.1 on 2026-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_task', models.TextField()),
                ('owner_id', models.BigIntegerField()),
            ],
        ),
    ]
