# Generated by Django 6.0.1 on 2026-01-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='category',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.TextField(default='main'),
            preserve_default=False,
        ),
    ]
