# Generated by Django 6.0.1 on 2026-01-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_completedtask_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 00:00'),
            preserve_default=False,
        ),
    ]
