# Generated by Django 6.0.1 on 2026-01-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_completedtask_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtask',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='completedtask',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=-1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
