# Generated by Django 6.0.1 on 2026-01-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_task_options_alter_completedtask_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
