# Generated by Django 6.0.1 on 2026-02-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_task_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtask',
            options={},
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='order',
        ),
    ]
