# Generated by Django 6.0.1 on 2026-02-08 10:47

import positions.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_completedtask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to=None,
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
